server:
  port: ${PORT:${SERVER_PORT:8848}}

spring:
  application:
    name: nacos-discovery-server
  cloud:
    nacos:
      discovery:
        server-addr: localhost:${server.port}
        namespace: public
        group: DEFAULT_GROUP
        metadata:
          version: 1.0.0
          env: dev

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always

logging:
  level:
    com.alibaba.nacos: INFO
    com.alibaba.cloud.nacos: INFO