# Grafana Datasource Configuration

apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    orgId: 1
    url: http://prometheus:9090
    basicAuth: false
    isDefault: true
    editable: true
    jsonData:
      timeInterval: "15s"

  - name: Nacos
    type: mysql
    access: proxy
    orgId: 1
    url: mysql:3306
    database: nacos_devtest
    user: nacos
    password: nacos
    isDefault: false
    editable: true
    jsonData:
      tlsAuth: false
      tlsAuthWithCACert: false